### PR TITLE
[WIP] Added a Method to append session details into req.cookies

### LINKED ISSUE #12: Method to check if user has logged in or not

### PR DESCRIPTION
**Pull request by aniketbiswas21**
# Issue Related with PR
- fixes #12 

# Proposed Changes
- To add a method that stores the user data in the req.cookies property after successful login

# Checklist

- [ ]  Implement a method to add session details in req.cookies property

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Actually I was struggling to make the req.cookies property globally added to all the req object. Can you help me with that/?

**Comment by sarthakkundra** [comment]
@aniketbiswas21 My Node is a little rusty but IMO you can use express cookie parser [npm package](https://www.npmjs.com/package/cookie-parser) or you can save the cookie in local storage and then fetch it wherever required.  @YashKumarVerma thoughts?

**Comment by aniketbiswas21** [comment]
> @aniketbiswas21 My Node is a little rusty but IMO you can use express cookie parser [npm package](https://www.npmjs.com/package/cookie-parser) or you can save the cookie in local storage and then fetch it wherever required. @YashKumarVerma thoughts?

Wouldn't saving the cookie cause problems? I am not sure like, it would saving a lot of user's info in the package.

**Comment by YashKumarVerma** [comment]
any updates

**Comment by aniketbiswas21** [comment]
@YashKumarVerma I am not able to figure out how to do this

**Comment by YashKumarVerma** [comment]
the middleware can write a cookie (that is generated on based on some unique item, like client id), and it stores the user id in the cookie. the middleware can intercept the cookie and check if user is authorized or not

**Comment by aniketbiswas21** [comment]
@YashKumarVerma I am not able to figure out how can I add the cookie property to every req object using middleware. In my current approach, it gets set once but for any subsequent request it returns undefined.

**Pull request closed without merging**
